name: ci_test
favicon: null
layout_spectrum: 0.14442781801335514
typography_spectrum: 0.973283507861197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a48f4c'
    - '#8c2317'
    - '#984a30'
    - '#cd9b9a'
  brandStrength: 1
  lightness: 0.5113954448606819
  saturation: 0.3222593062091619
  rhythmicContrast: 0.3147932298015803
purpose: []
